### ISSUE TITLE
Horizontal editor scroll isn't being themed with Intellij 19 beta

### ISSUE THREAD

**Issue by rlubke** [ChrisRM/material-theme-jetbrains#1160]
### Summary

Horizontal scroll isn't being themed.  Using Solarized Dark as my theme, but the horizontal scroll is white (see screenshot).

### Expected behavior

Horizontal scroll should be themed the same as vertical

### Actual behavior

Screenshot:  https://www.dropbox.com/s/tmk78klycms9pts/Screen%20Shot%202019-03-19%20at%2006.45.04.png?dl=0

### Environment

IntelliJ IDEA 2019.1 Beta (Ultimate Edition)
Build #IU-191.6183.20, built on March 13, 2019
IntelliJ IDEA EAP User
Expiration date: April 12, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by mallowigi** [comment]
Scroll bars are from the color scheme. Please reset to defaults or change the values manually in the color scheme options.

**Comment by rlubke** [comment]
The vertical scroll bar is properly themed.  I've reset to the defaults and it has had no effect.

**Comment by mallowigi** [comment]
Will check.

**Comment by mallowigi** [comment]
Cannot reproduce. Please contact me on Slack for more troubleshooting

**Comment by adanperez** [comment]
I am seeing the same issue on
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019

Any setting I am missing?

**Comment by mallowigi** [comment]
Look in “Settings > Editor > Color schemes > Scrollbars” if it’s themed.

**Comment by adanperez** [comment]
@mallowigi I have no colors being applied there.  I've attached an image of what I am seeing.
![issue](https://user-images.githubusercontent.com/444935/55158247-6ff13380-512c-11e9-9584-ddb038891c07.png) 
 I am on OSX Mojave

**Comment by Bodil-X** [comment]
> Look in “Settings > Editor > Color schemes > Scrollbars” if it’s themed.

hi, @mallowigi 
i am seeing the same issue on 2019.1 (Mac Mojave 10.14.3), and i can't found "Scrollbars" setting in "Settings > Editor > Color schemes". but i reset the theme to Decular, the issue disappear.

**Comment by anotherjames** [comment]
http://www.jetbrains.org/intellij/sdk/docs/reference_guide/ui_themes/themes_extras.html#customizing-editor-scroll-bar-colors scrollbars can now be customised from UI plugins, as of 2019.1. 

I also got around this by changing the parent theme of my own custom theme to Darcula, since that already customises the scrollbars to be dark, is that something applicable here?

**Comment by woj-tek** [comment]
Idea 2019.1
macOS Mojave
theme: Dracula (since forever)

Same issue - horizontal scroolbar is not themed. I re-applied Dracula and it's still white.

**Comment by mallowigi** [comment]
This has been fixed in 3.9.0.3

**Comment by s-dezign** [comment]
I found the solution: 
In JetBrains go to Preferences -> Editor -> Color Scheme -> Click on a Gear Icon -> Export... -> IDEA color scheme ( .icls )

Then find that file and change it to .xml -> Open in any text editor and modify the very top line: 

`<scheme name="Custom Schema" version="142" parent_scheme="Darcula">`

The fix is to make `parent_scheme` any default dark based like Darcula in my case.
Then it fixing scrolling bars themes.

**Comment by sebastiaanluca** [comment]
> The fix is to make parent_scheme any default dark based like Darcula in my case.

This didn't work for me, still getting the default horizontal scrollbars.

PhpStorm 2019.1.2 Preview
Build #PS-191.7141.35, built on May 2, 2019
JRE: 1.8.0_202-release-1483-b49 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

**Comment by sebastiaanluca** [comment]
@adanperez This fixed the scrollbars, but messed up various other code editor colors 😅

**Comment by davNazaryan** [comment]
Faced problem with horizontal scrollbar being light while vertical one is okay.
The problem appears after MacOS update 11.5.2. Using WebStorm 2021.2.1

I have my own custom theme based on Opsidian++.
I just select another theme from `Editor -> Color Scheme` save it and select my custom theme back.

Hope this will help someone.
