### ISSUE TITLE
Git changes indicator not working right.

### ISSUE THREAD

**Issue by ProjectInfinity** [ChrisRM/material-theme-jetbrains#12]
With material theme: ![](http://puu.sh/kzArm/a3aaea7d01.png)
With Darcula: ![](http://puu.sh/kzAxE/9b29a619c8.png)

Also, what....?!
![](http://puu.sh/kzABa/86ca4098db.png)
![](http://puu.sh/kzADQ/19e22ae92e.png)

Is a new THEME supposed to be installed? Cause I don't have a material theme, only a material scheme.

**Comment by ChrisRM** [comment]
are you talking about the color in the gutter?

**Comment by ProjectInfinity** [comment]
Yes, that indicates changed/new lines when you have a git-enabled project.

**Comment by ChrisRM** [comment]
I'll fix that.

**Comment by ProjectInfinity** [comment]
Missed out that you said it should install a theme. It did not for me. Only the scheme, running Windows 10 with JDK 1.8, all 64bit.

**Comment by xFlatlinex** [comment]
This is just a configuration issue, the colors are way to subtle but can easily be changed in the config. What I do see as a problem is that I even though I can create a custom theme using the "save as..." feature, PhpStorm won't use that one in favor of the one in the plugin the next time I open it.

**Comment by ProjectInfinity** [comment]
@xFlatlinex Explain how this is a configuration issue? I just proved in the last two images that it's broken.

Removing the first comment marks the next lines as altered, even though ALL of them should have been marked as altered. This does not happen on default Darcula.

**Comment by xFlatlinex** [comment]
@ProjectInfinity re-read your first message because I thought you were referring just to the color. The issue you mention is not happening to me, or at least I didn't notice it yet.

**Comment by ProjectInfinity** [comment]
@xFlatlinex If you look at the images there are no changed lines marked when using Material. The one you can see is actually *new* lines and not altered. It's a bit confusing maybe, but yes. Definitely not a case of too subtle colors. :)

**Comment by xFlatlinex** [comment]
@ProjectInfinity hehe yea, got it now, thanks for the clarification.

And I still think this is a configuration issue, let me explain:

When I edit a line, it looks like it doesn't mark it in the gutter, but it actually is, because in `Gutter > Modified lines` the background is disabled:

![gutter-modified-lines-color](https://cloud.githubusercontent.com/assets/1039580/10316288/f312d0ba-6c34-11e5-810b-02230f0400a9.png)

But if I modify that setting a background color:

![gutter-modified-lines-color-set](https://cloud.githubusercontent.com/assets/1039580/10316331/2a555944-6c35-11e5-826f-ea41e54981e7.png)

The color in the gutter shows up:

![gutter-modified-added-lines](https://cloud.githubusercontent.com/assets/1039580/10316428/98c78d7a-6c35-11e5-9dd9-d1f7a1fed520.png)


_Notice I modified both colors and I had to save the modifications to a copy of the theme since it doesn't let me modify the one in the plugin._

**Comment by ChrisRM** [comment]
Fixed in the newest build

**Comment by ProjectInfinity** [comment]
Wasn't this supposed to create a theme? It still doesn't.

![](http://puu.sh/kEnA6/b707bd0041.png)

Not to mention that the issue still does not appear fixed when reinstalling the latest release. I had to create my own scheme and do the fix that @xFlatlinex specified.

**Comment by ChrisRM** [comment]
Indeed it should. I'm on it

**Comment by ChrisRM** [comment]
@ProjectInfinity What IDE and version are you on using?

**Comment by ProjectInfinity** [comment]
@ChrisRM PhpStorm 9.0.2 141.2462
