### ISSUE TITLE
Some icons are broken

### ISSUE THREAD

**Issue by alexsergin** [ChrisRM/material-theme-jetbrains#1448]
### Summary

Some icons are broken and displays as a black dot. For example breakpoints, run icon on debug panel and some icons on touch bar on mac pro but the most of that are from plugins (e.g. merge request creation button of gitlab plugin https://plugins.jetbrains.com/plugin/7975-gitlab-projects/)

Screenshots:
https://prnt.sc/q3y5j9
https://prnt.sc/q3y5zj

### Environment

IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Licensed to Maxim Blodyrev
Subscription is active until March 5, 2020
For educational use only.
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: BashSupport, JAXB 2.0 XJC generator, JProfiler, Jetbrains TeamCity Plugin, Lombook Plugin, com.chrisrm.idea.MaterialThemeUI, com.ppolivka.gitlabprojects, com.wakatime.intellij.plugin, io.protostuff.protostuff-jetbrains-plugin, mobi.hsz.idea.gitignore, net.ashald.envfile, org.intellij.scala, org.jetbrains.plugins.vue

**Comment by mallowigi** [comment]
While I do see those issues from time to time, it is usually inconsistent and do not repeat all the time. However for 3rd party plugins, it could well be the case, so if you have a list that I can check of, that would be great.

**Comment by alexsergin** [comment]
@mallowigi Actually it's very common issue coz my coworkers have it on android studio and my friend have on php storm too. So I think it doesn't depend of plugins, but... if you asking:)
I have enabled all bundled plugins and all non-bundled plugins described in the environment section in my first message. All of that are updated to the last version. Unfortunately I don't know where to find full enabled plugin list from config, so if you'll tell me I do that.

**Comment by mallowigi** [comment]
fixed

**Comment by alexsergin** [comment]
@mallowigi Doesn't work for me with mac pro's touch bar & GitLab Projects plugin (https://plugins.jetbrains.com/plugin/7975-gitlab-projects/). Still seeing black dot on touch bar for merge request creation button.
Here is the screenshot https://prnt.sc/qcked5

**Comment by mallowigi** [comment]
You’re on 4.11.4 right?

**Comment by alexsergin** [comment]
@mallowigi Yep. Latest updates are installed. And restarted IDE few times.

**Comment by mallowigi** [comment]
I installed Gitlab projects, added the icon to the touch bar and I am still seeing the icon. Can you share your custom touch bar settings ?

**Comment by alexsergin** [comment]
I think it happens because I have this icon on touch bar with option button pressed only. Seems it doesn't render it by default and that render process isn't starting for the alternative touch bar. Can you check this case on your side please?
Here is a screenshot with my touch bar settings https://prnt.sc/qd4n34

**Comment by alexsergin** [comment]
@mallowigi

**Comment by derekhendrickx** [comment]
I also have this issue with Goland.

![icon-issue](https://user-images.githubusercontent.com/1218149/71933179-832b3800-316f-11ea-997c-ef57773ea0c2.jpg)

**Comment by alexsergin** [comment]
@derekhendrickx It actually not depends on IDE as I told already. My friends have this issue on phpstorm and android studio too. It seems a bug in material ui theme.

**Comment by alexsergin** [comment]
Hi there. Any updates on this issue? It's still there((

**Comment by mallowigi** [comment]
Again, I need reproducible steps.

**Comment by alexsergin** [comment]
@mallowigi Just try to add merge request creation button from GitLab Projects plugin onto default touch bar with alt key. Here is a screenshot of my touchbar configuration https://prnt.sc/qqn1q6

I also have the same issue with default editor split buttons if it was added onto touch bar with any optional key. Here is a screenshot of this config https://prnt.sc/qqn32u

**Comment by mallowigi** [comment]
Please follow this issue: https://youtrack.jetbrains.com/issue/IDEA-224406
