### ISSUE TITLE
[IntelliJ 2020.1 EAP] Path to current file view tiles are compressed into themselves

### ISSUE THREAD

**Issue by GavinRay97** [ChrisRM/material-theme-jetbrains#1507]
In RubyMine 2019.3.2, the path to current file displays correctly:
![image](https://user-images.githubusercontent.com/26604994/73192053-7f4b5f80-40f6-11ea-9256-b9123347c182.png)

In IntelliJ 2020.1 EAP however, it displays like this:
![image](https://user-images.githubusercontent.com/26604994/73191990-6642ae80-40f6-11ea-9ae5-fbf1e4ed502c.png)

They should have identical settings, so I _think_ it's not user error on my end.

Edit: It seems to be a general issue with the arrows separating horizontal entries in a row of items:

![image](https://user-images.githubusercontent.com/26604994/73196473-a0637e80-40fd-11ea-907f-07d790029660.png)

**Comment by GavinRay97** [comment]
Fixed in `4.13.1` release today :ok_hand:

**Comment by Benjozork** [comment]
It still shows weridly for me:
![image](https://user-images.githubusercontent.com/4503241/75600539-5b28c880-5a7e-11ea-8747-94902d0661d9.png)
