### ISSUE TITLE
After updating to IDEA 201.5616.10, my material theme keeps switching to "Material darker"

### ISSUE THREAD

**Issue by gabrielshanahan** [ChrisRM/material-theme-jetbrains#1526]
Hey everyone,

Steps to reproduce (using Material Theme 5.0.0):

1.  Open settings, under "Appearance & Behaviour" select "Material Theme" and change selected theme to "Arc Dark" (or anything else).
2. Exit IDEA and start it up again

Expected behavior: The theme is still set to whatever you picked in step 1
Observed behavior: The theme is set to "Material Darker"

If I revert to 201.5259.13, this does not occur.

Kind regards,

Gabriel

### Environment

IntelliJ IDEA 2020.1 EAP (Community Edition)
Build #IC-201.5616.10, built on February 19, 2020
Runtime version: 11.0.6+8-b722.15 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.tooltip.initialDelay=368, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.codestream.jetbrains-codestream, training, izhangzhihao.rainbow.brackets, com.chrisrm.idea.MaterialThemeUI, com.jetbrains.edu
to the clipboard and paste it here.

**material_theme.xml**
```
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="accentColor" value="42a5f5" />
    <option name="selectedTheme" value="ARC_DARK" />
    <option name="userId" value="16177fcf:16efb549283:-8000" />
    <option name="version" value="1.3.0" />
  </component>
</application>%
```

**Comment by mirrana** [comment]
I'm having a similar problem, except it always reverts back to the built-in Darcula theme when I restart IDEA. No idea if this is an IDEA problem or a Material Theme problem.

**Comment by mallowigi** [comment]
I know why it happens! Dang it. I will fix it for next version. In the meanwhile please use the Material Theme Switcher or the Theme dropdown in the Appearance settings.

**Comment by mallowigi** [comment]
fixed

**Comment by icawebdesign** [comment]
This still appears to be an issue with 5.1.0 and 2020.1 5616.33.. continually reverts to Arc Darker.

**Comment by mallowigi** [comment]
Yeah it seems my fix made it even worse... I submitted an hotfix but other issues came up as well. 

I’ll try to fix it with a calm mind during the weekend. In the meantime 5.1.1 should have fixed that issue

**Comment by icawebdesign** [comment]
@mallowigi It kind of has... the IDE theme looks now to be resolved, but it appears that the latest versions override the editor colour scheme on restart.

I use one of the Rainglow colour schemes for the editor itself. Changing the Material Theme to Atom One Dark for example as I just have and using one of the Rainglow themes for the editor colour scheme. Restart PhpStorm and my editor colour scheme has also been reset to Arc One Dark.. so looks like you're halfway there =)

No immediate rush.. I appreciate the work you do on this... as and when you can is good enough IMO.

**Comment by icawebdesign** [comment]
@mallowigi just updated to 5.1.2 and this appears to have resolved the editor colour scheme being overridden by the material theme setting on (re)start.

Many thanks for fixing this quickly 👍
