### ISSUE TITLE
Theme only works in editor in pycharm 2020.1 not in any of tool windows. 

### ISSUE THREAD

**Issue by yunti** [ChrisRM/material-theme-jetbrains#1585]
### Summary

After upgrading to pycharm 2020.1 the material theme is now broken and only themes on the editor - all tool window , file explorer etc are unthemed. 

### Expected behavior
All IDE would be themed as it was in 2019.3
...

### Steps to reproduce (if needed)
Happened immediately after automated upgrade.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/1826271/81166650-c06fcd00-8f8b-11ea-8690-00f44d46009c.png">

Y

### Environment
PyCharm 2020.1 (Professional Edition)
Build #PY-201.6668.115, built on April 7, 2020
Licensed to XXX
Subscription is active until December 17, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: editor.distraction.free.mode=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: AceJump, IdeaVIM, org.jetbrains.IdeaVim-EasyMotion, com.alicannklc.tailwind, com.chrisrm.idea.MaterialThemeUI, mobi.hsz.idea.gitignore, NodeJS, com.jetbrains.intellij.datalore, ru.adelf.idea.dotenv, ru.meanmail.plugin.requirements, org.toml.lang

From material_theme.xml

```
<application>
  <component name="MaterialThemeConfig">
    <option name="contrastMode" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="416a9b" />
    <option name="selectedTheme" value="NATIVE" />
    <option name="userId" value="-3255c740:16d8c5ef846:-8000" />
    <option name="version" value="5.2.0" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Please update to the latest version and tell me the results

**Comment by yunti** [comment]
Thanks just updated to the latest version but no change unfortunately

**Comment by nonickDev** [comment]
this is same issue, [1583](https://github.com/ChrisRM/material-theme-jetbrains/issues/1583)

**Comment by mallowigi** [comment]
think i've fixed it. Please check with last version

**Comment by Thomas-Negrault** [comment]
I had the same issue, updating did not fix it but I changed my theme to another one and then change it back and it's working fine now

**Comment by yunti** [comment]
@mallowigi Thanks quickly fixing.  I can't see a new release from today, in github or via the IDE. What version number is the fix in? I currently have 5.3.2.1 installed.

**Comment by yunti** [comment]
Changing the theme via Tools-> Material Theme and changing it back as @Thomas-Negrault suggested worked.
