### ISSUE TITLE
Tab highlight and thickness not working with the latest EAP

### ISSUE THREAD

**Issue by lllopo** [ChrisRM/material-theme-jetbrains#1651]
### Summary
Tab highlight and thickness are messed up with the latest (two) EAP.

### Expected behavior
Settings are highlight at top and thickness of 1px and well ... that's expected.

### Actual behavior
Thickness is the default and both top and default highlights are visible :

![Screenshot 2020-11-07 103036](https://user-images.githubusercontent.com/5485902/98436595-4c9eb080-20e5-11eb-806f-3fd94b1c95bf.png)

### Steps to reproduce (if needed)
Set thickness to any than default and highlight position to any than default. This problem appeared with the previous EAP and was not fixed nether by the latest EAP or the latest Material Plugin UI update that came along with it. I haven't touched my settings since the last working versions of both.

### Environment
PhpStorm 2020.3 EAP
Build #PS-203.5600.44, built on November 6, 2020
Runtime version: 11.0.8+10-b1145.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
Material Theme UI 5.5.0

**Comment by lllopo** [comment]
Update : issue persists with v. 5.5.1 - no change.

**Comment by mallowigi** [comment]
haven't checked that yet

**Comment by mallowigi** [comment]
done

**Comment by lllopo** [comment]
@mallowigi Checked the fix with the latest update. The bottom highlight disappeared, but the thickness is still not ok. It seems to be +1px as even if I make it 2px it appears 3px. Also - #1473 is still there and definitely comes from material theme as it appears right when the theming of the tabs gets activated.

![Screenshot 2021-01-03 114631](https://user-images.githubusercontent.com/5485902/103475885-db643c80-4db9-11eb-83f7-afc2ea6f10a4.png)

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/103486121-03788d80-4e04-11eb-8c6e-7f4c4f055ee5.png)

ok i dont remember why i did this lol
