### ISSUE TITLE
Problem with font color in Github theme

### ISSUE THREAD

**Issue by vaskolukas** [ChrisRM/material-theme-jetbrains#1688]
### Summary

I am using Github theme in PHPStorm. When I autocomplete some elements for example `<a>` element, cursor automatically jumps into `href` attribute, but I cannot see what I am typing because its's highlighted and the font has white color. After pressing `ESC` on keyboard, highlight dissapeard and I can see what I typed. This happends also for example with <img> element and src attribute or also while typing `@media` query in css.

In this picture i generated element whit `TAB` key and start writing some `href`:
![image](https://user-images.githubusercontent.com/16058658/106774927-ed4c3000-6642-11eb-84bd-a95deb87f782.png)

After pressing `ESC` I can see what is there:
![image](https://user-images.githubusercontent.com/16058658/106775073-110f7600-6643-11eb-8f6c-4f6d36c436f8.png)

Again with css `@media` query:
![image](https://user-images.githubusercontent.com/16058658/106775123-1d93ce80-6643-11eb-8e80-8856ed7ca4a2.png)

And after pressing `ESC`:
![image](https://user-images.githubusercontent.com/16058658/106775146-22f11900-6643-11eb-8e13-27f145f044bb.png)

This happends only with Github theme, as I tried to change theme to couple others and it was fine in them.

So I am not sure if I have something wrong set up in theme or it is some kind of bug.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

PhpStorm 2020.3
Build #PS-203.5981.175, built on December 2, 2020
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1960M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.mallowigi, ru.adelf.idea.dotenv

Not sure if this is what you want for config: https://pastebin.com/A7ygQZJi

**Comment by mallowigi** [comment]
This issue has been fixed in subsequent versions, unfortunately I'm not releasing updates for older versions.

You can try to fix it yourself by changing the value at 

```
<option name="LIVE_TEMPLATE_ATTRIBUTES">
            <value>
                <option name="FOREGROUND" value="ffffff"/> -> to 111111
                <option name="BACKGROUND" value="79cb6050"/>
            </value>
        </option>
```
in Github.xml

Or change the "Live Template" value in the Color Schemes panel

**Comment by vaskolukas** [comment]
Hi, just updated PHPStorm to newest version, but the bug is still there.

PhpStorm 2020.3.2
Build #PS-203.7148.74, built on January 27, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1960M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.mallowigi, ru.adelf.idea.dotenv

**Comment by mallowigi** [comment]
> Hi, just updated PHPStorm to newest version, but the bug is still there.
> 
> PhpStorm 2020.3.2
> Build #PS-203.7148.74, built on January 27, 2021
> Runtime version: 11.0.9.1+11-b1145.77 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Windows 10 10.0
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1960M
> Cores: 12
> Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
> Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.mallowigi, ru.adelf.idea.dotenv

By latest version I meant the versions for 2021.1. I'm not releasing new versions for 2020 as it is hard to manage.
