### ISSUE TITLE
Sporadic NullPointerException when used with Rider

### ISSUE THREAD

**Issue by gareth-cross** [ChrisRM/material-theme-jetbrains#1734]
### Summary

I am using Material Theme 6.3.2 w/ Rider for Unreal Engine 2021.1 (it is currently in Beta, but I would imagine similar to ordinary Rider, probably?) Periodically the theme vanishes and the IDE reverts to the default theme. On relaunch, it notifies me that the Material Plugin hit a NullPointerException.

### Expected behavior

- No null pointer exception.

### Actual behavior

Stack trace:
```
5u6s 95zm trj2java.lang.NullPointerException
	at com.intellij.ui.components.BasicOptionButtonUI.getOptionButton(BasicOptionButtonUI.kt:43)
	at com.intellij.ui.components.BasicOptionButtonUI$BaseButton.getBackground(BasicOptionButtonUI.kt:324)
	at java.desktop/javax.swing.JComponent.setBackground(JComponent.java:2754)
	at com.mallowigi.idea.utils.ButtonBackgroundTimer.lambda$getActionListener$0(ButtonBackgroundTimer.java:53)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:973)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Steps to reproduce (if needed)

Unfortunately it appears to be mostly random. I'll leave the IDE for a while and come back to it, and the theme has switched. I'm not sure what to do to reproduce it.

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

```
Rider for Unreal Engine 2021.1
Build #RDCPPP-211.6085.159, built on March 1, 2021
Subscription is active until August 31, 2021.
Runtime version: 11.0.10+9-b1341.2 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
.NET Framework 4.0.30319.42000
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 24
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, ea.enable.developers.list=false, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.balloon.shadow.size=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI (6.3.2)
```

Config file:
```
<application>
  <component name="MaterialThemeConfig">
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="accentColor" value="84ffff" />
    <option name="selectedTheme" value="DEEPOCEAN" />
    <option name="userId" value="-2e8158f2:178e903273b:-8000" />
    <option name="version" value="6.3.2" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
I think I fixed this issue in 6.3.3, please update and check

**Comment by lzybkr** [comment]
I'm seeing the same with 6.3.3:

![image](https://user-images.githubusercontent.com/2148248/116285932-8622b100-a743-11eb-8541-59af29975bfc.png)

**Comment by gareth-cross** [comment]
Confirmed. I upgraded as well and also see this issue still.
