### ISSUE TITLE
from, as, log and other words are not colored

### ISSUE THREAD

**Issue by iCrowned** [ChrisRM/material-theme-jetbrains#1788]
### Summary
The keywords such as "from", "as" are not colored when "import" is
The same with function, static
...

### Expected behavior

They are expected to be colored :)

![ScreenShot WebStorm 2021-07-02](https://user-images.githubusercontent.com/80093436/124192013-4a9ebd00-dacd-11eb-8de4-ce61741e4c7e.png)
![ScreenShot WebStorm 2021-07-02](https://user-images.githubusercontent.com/80093436/124192027-4f637100-dacd-11eb-8d51-66bfb7c52f0e.png)
![ScreenShot WebStorm 2021-07-02](https://user-images.githubusercontent.com/80093436/124191870-1925f180-dacd-11eb-9877-b45870ce7074.png)
![ScreenShot WebStorm 2021-07-02](https://user-images.githubusercontent.com/80093436/124193436-7ae75b00-dacf-11eb-8440-223a2a8df683.png)

![ScreenShot WebStorm 2021-07-02](https://user-images.githubusercontent.com/80093436/124192847-a0279980-dace-11eb-9a42-ccae7912c370.png)
Plugin Version 6.7.0
* Plugin configuration (found in material_theme.xml)
[material_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/6750951/material_theme.zip)

**Comment by mallowigi** [comment]
https://www.material-theme.com/docs/configuration/color-scheme-additions/#enforce-highlighting

**Comment by rasulomaroff** [comment]
> https://www.material-theme.com/docs/configuration/color-scheme-additions/#enforce-highlighting
I tried this, but it didn't help with console.log and some other language additions

**Comment by mallowigi** [comment]
I just checked, it should have been fixed in version 6.7.0

**Comment by iCrowned** [comment]
> I just checked, it should have been fixed in version 6.7.0

I was updated at the moment of the screenshot and this problem wasn't fixed :(

**Comment by mallowigi** [comment]
Can you provide more information about your environment?

**Comment by iCrowned** [comment]
> Can you provide more information about your environment?

You mean this?
<img width="608" alt="ScreenShot CleanShot 2021-07-04" src="https://user-images.githubusercontent.com/80093436/124384238-f7995580-dcd8-11eb-8ebc-ceba62b3463a.png">
