### ISSUE TITLE
Extra blank space when Project Frame is enabled

### ISSUE THREAD

**Issue by yurique** [ChrisRM/material-theme-jetbrains#1797]
### Summary

When enabling the project frame I'm getting a blank space between the coloured project stripe and the editor.

### Expected behavior

No extra blank space.

### Actual behavior

There is an extra blank space :). If I disable the project frame, the extra blank space goes away as well.

### Steps to reproduce (if needed)

1. Enable Project Frame

![image](https://user-images.githubusercontent.com/919230/125782258-cb9dd6e6-9fdf-44dc-bf7d-9d61ce0a50ca.png)

### Environment

```
IntelliJ IDEA 2021.1.3 (Ultimate Edition)
Build #IU-211.7628.21, built on June 30, 2021
Runtime version: 11.0.11+9-b1341.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 20
Registry: ide.balloon.shadow.size=0, scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: org.intellij.plugins.postcss (211.6693.64), com.mallowigi (36.0), name.kropp.intellij.makefile (211.7628.1), org.jetbrains.plugins.hocon (2021.1.0), pro.bashsupport (1.5.20.211), org.jetbrains.kotlin (211-1.5.20-release-284-IJ7442.40), com.jetbrains.lang.ejs (211.6693.65), intellij.prettierJS (211.7142.13), com.chrisrm.idea.MaterialThemeUI (6.7.2), org.intellij.scala (2021.1.386), com.intellij.lang.jsgraphql (2.9.1), Pythonid (211.7628.24), org.jetbrains.plugins.go (211.7628.1), ru.adelf.idea.dotenv (2021.2)
Kotlin: 211-1.5.20-release-284-IJ7442.40
```

[theme-config.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/6822814/theme-config.zip)

**Comment by mallowigi** [comment]
This has been fixed in 2021.2 versions, so please wait a bit, the release is around the corner

**Comment by yurique** [comment]
Awesome! Thanks @mallowigi!

**Comment by yurique** [comment]
I got the 2021.2 update and the issue is still here :)

One extra thing I've noticed, though – it depends on the UI font size (and maybe the font itself?)

I'm using the monospaced font for the UI font (not only the editor) and I had it's size set to 20 👓 – this way I have that blank space very visible, as on the screenshots above.

![image](https://user-images.githubusercontent.com/919230/127903428-084b61c8-104c-4875-9f4d-87dd086ffd02.png)

 After reducing the UI font size down to 16 – the blank space is still there, but it's barely noticeable (and I don't mind having it that way).

![image](https://user-images.githubusercontent.com/919230/127903492-9d5f6d62-05bc-4ba6-9e05-4d69b06961da.png)

**Comment by mallowigi** [comment]
I am not able to reproduce, can you come over on Slack so I can see how can I reproduce your setup?
