### ISSUE TITLE
Can't keep appearance font setting ?

### ISSUE THREAD

**Issue by agileago** [ChrisRM/material-theme-jetbrains#230]
![image](https://cloud.githubusercontent.com/assets/11799110/17406844/af344106-5a97-11e6-9462-e281b6c0967d.png)
![image](https://cloud.githubusercontent.com/assets/11799110/17406939/10707a0c-5a98-11e6-9ace-3e9fa811254e.png)

when i set the appearance font. it is work right now. but when i  restart the project. it is not work.

**Comment by IceMan81** [comment]
I've the same issue.

**Comment by houzixiashanxiedaima** [comment]
me too , i want to change the default font to Monaco, but did not work.

**Comment by SalahAdDin** [comment]
But, i could change the font to `Dejabu for Powerline` with no problems.

**Comment by agileago** [comment]
@SalahAdDin  when you reopen the project. the font also keep ?

**Comment by SalahAdDin** [comment]
I think so.

**Comment by agileago** [comment]
it looks like your ide is so different with us

**Comment by houzixiashanxiedaima** [comment]
@SalahAdDin  my ide is Android Studio 2.1.1，OS is Windows 10 , you are the same with me ?

**Comment by SalahAdDin** [comment]
No, my ID is WebStorm and PyCharm.

**Comment by Rukuki** [comment]
Yep, have to change appearance font size every time ide starts due to hidpi

**Comment by victorlapshev** [comment]
got same issue, any ideas?

**Comment by agileago** [comment]
Maybe @ChrisRM is so busy that have no time to see this issue.😱

**Comment by Erwyn** [comment]
Same here on Linux with IntelliJ.

**Comment by SalahAdDin** [comment]
:O

**Comment by unixc3t** [comment]
I've the same issue.

Summary

I install the theme and reset idea . the theme activate ,but the theme ui font is changed, it doesn't use my default font
the error font is activated when i change the ui and restart idea
![b1676dfe-7ac2-11e6-9720-db3afeb33ca0](https://cloud.githubusercontent.com/assets/4446148/18571986/7f935f36-7be9-11e6-9d62-662440082722.png)


Expected behavior

I change the theme 
the Appearance > default font is Comic Sans Ms
I want the new ui font is Comic Sans Ms

Actual behavior

1 I change the theme 
2 the Appearance > default font is Comic Sans Ms
3 but the new ui font actual is other font

4 I change the font is Comic Sans Ms and restart idea
5 I open the idea ,it's can't apply my Comic Sans Ms ,I have to set the default font again

Environment

ubuntu 16.04 64bit

###Tools
Idea community 2016.2.4

Material Theme release: 1.4.4
sorry ,I am english is weak

**Comment by andrzejsliwa** [comment]
@ChrisRM could you point us with this issue, maybe we will be able to solve it. Do have any clue what problem can be or how to debug it?

**Comment by ChrisRM** [comment]
This should be fixed in the latest build. Try reinstalling the plugin or download the [Material Theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/raw/master/Material%20Theme.zip) and install it manually.

I'm hoping to release 0.2.2 during the weekend.

**Comment by andrzejsliwa** [comment]
@ChrisRM I reinstalled it, than again download this file and installed it manually. Still broken.

**Comment by ChrisRM** [comment]
Can you guys test to see if this still is a problem?

**Comment by mallowigi** [comment]
Yes, it is still a problem

**Comment by mallowigi** [comment]
@ChrisRM I fixed the issue in my latest PR. plz review

**Comment by gencer** [comment]
@mallowigi could you kindly build your PR and provide a zip for us? Currently i am failed to build against my environment.

**Comment by mallowigi** [comment]
I haven't tested it, but there you go.

**Comment by gencer** [comment]
@mallowigi, should I expect a file after that sentence? You said '...there you go' but I can't see any links.

**Comment by thebasix** [comment]
@gencer 
https://github.com/ChrisRM/material-theme-jetbrains/pull/279

**Comment by gencer** [comment]
@thebasix, oh didn't catch that. I verify that it is working.

**Comment by denofevil** [comment]
Duplicates #54

**Comment by wxweven** [comment]
This problem bothers me a lot，so I changed the properties file of Idea （on Mac）
~/Library/Preferences/IntelliJIdea2019.2/options/ui.lnf.xml
<application>
  <component name="UISettings">
    <option name="ACTIVATE_MRU_EDITOR_ON_CLOSE" value="true" />
    <option name="FONT_FACE" value="Monaco" />
    <option name="FONT_SCALE" value="1.0" />
    <option name="FONT_SIZE" value="18" />
    <option name="MARK_MODIFIED_TABS_WITH_ASTERISK" value="true" />
    <option name="OVERRIDE_NONIDEA_LAF_FONTS" value="true" />
  </component>
</application>

change the FONT_FACE and FONT_SIZE of this file，restart your idea, probles solved
