### ISSUE TITLE
Random color changes in fonts renders them invisible.

### ISSUE THREAD

**Issue by vpassapera** [ChrisRM/material-theme-jetbrains#343]
### Summary

Randomly, my IDE gets very low contrast when using dark color schemes...meaning the color for source files in the file tree, and any pop-up text fields in the application becomes nearly invisible.
I have to highlight text to be able to see it.

![Imgur](http://i.imgur.com/AwtfBMF.png)

### Expected behavior

No random changes in contrast should happen in color.

### Actual behavior

IDE randomly changes color of fonts for themes, making them impossible to see in text boxes and file tree.

### Steps to reproduce

1. Install material theme ui plugin and select (Darker, Default, Palenight)
2. Go to File/PhpStorm > Settings/Preferences > Editor > Colors & Fonts
3. Select any item installed in colors directory.
4. Work away....sometimes happens fast, other times happens at a later point.

* Operating system and version:
  * [X] Mac OS 10.11.6
  * [X] Linux Ubuntu Gnome 17.04
* Material Theme release:
  * v. 0.3.0.1
* PHPStorm/IntelliJ Version
  * PHPStorm 2017.1.4 (#PS-171.4694.2)

**Comment by vpassapera** [comment]
Downgraded to previous version for now, since it doesn't have these problems.

**Comment by mallowigi** [comment]
You probably have an edited version of the color schemes. Try to restore defaults (Settings> Colors & Fonts > Gear icon > Restore defaults), the color scheme should revert to white instead of blue. If it doesn't you will have to delete the copies manually (Finder > Library > Preferences > PHPStorm > colors and delete the "@user" color schemes) and restart the IDE after selecting Default or Darcula.

**Comment by vpassapera** [comment]
I do...that's part of the bug.

### Steps to reproduce

1. Install material theme ui plugin and select (Darker, Default, Palenight)
2. Go to File/PhpStorm > Settings/Preferences > Editor > Colors & Fonts
3. Select any item installed in colors directory. <---- these are custom color schemes
4. Work away....sometimes happens fast, other times happens at a later point.

**Comment by mallowigi** [comment]
Is it fixed in the latest release?

**Comment by vpassapera** [comment]
No sir it is not. It still shows the dark text on dark background when selecting a light ICLS theme.

**Comment by mallowigi** [comment]
I understand now the issue, however as you can see in the following screenshot:

http://i.imgur.com/kJ2Lrko.png

This is an issue that happens with the Darcula LAF as well

I think this is an issue with Light themes when used with Darcula LAF, and since the Material Theme LAF is based off Darcula, so the issue happens as well.

This being said, maybe there is a way to fix it anyway without fixing the Darcula issue :)

Will keep you posted

**Comment by vpassapera** [comment]
Ty!

**Comment by mallowigi** [comment]
Could not find a way, sorry. At the very least you can still open a bug request to Jetbrains.
