### ISSUE TITLE
IDE preferences panels broken after trying to switch IDE Themes

### ISSUE THREAD

**Issue by ptrkcsk** [ChrisRM/material-theme-jetbrains#436]
# Summary

I'm experiencing a major bug after updating to Material Theme UI v0.10.4 (PhpStorm reports Material Theme UI as v0.10.4, though I only see v0.10.3 in the changelog). Switching to a new IDE Theme causes Material Theme UI exception, which causes an 'IDE Fatal Error', which breaks Color Scheme preferences. I have to restart the IDE to recover.

# Steps to reproduce

1. Start the IDE.
2. Try to go to Color Scheme or Plugins preferences panels (they should work).
3. Try to switch to a new IDE Theme via Tools → Material Theme → Material Theme Chooser (Every theme causes the bug *except* Lighter Theme.)
4. See 'IDE Fatal Error' notification caused by Material Theme UI exception.
5. Try to go to Color Scheme or Plugins preferences panels again. This time they are broken (see screenshot below).

![screenshot 2017-09-12 14 36 00](https://user-images.githubusercontent.com/4766244/30349561-375d5108-97c8-11e7-8957-34d7d2e7498d.png)

# Environment

PhpStorm 2017.2.3
Build #PS-172.4155.25, built on September 5, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
Material Theme UI v0.10.4 (?)

# Stack trace

```
null
java.lang.NullPointerException
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1644)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1273)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:276)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1503)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1261)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:253)
	at javax.swing.text.html.StyleSheet$ViewAttributeSet.<init>(StyleSheet.java:2673)
	at javax.swing.text.html.StyleSheet.getViewAttributes(StyleSheet.java:348)
	at javax.swing.text.html.ParagraphView.setPropertiesFromAttributes(ParagraphView.java:101)
	at javax.swing.text.ParagraphView.<init>(ParagraphView.java:59)
	at javax.swing.text.html.ParagraphView.<init>(ParagraphView.java:54)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory.create(HTMLEditorKit.java:1148)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:112)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory$BodyBlockView.setParent(HTMLEditorKit.java:1327)
	at javax.swing.text.CompositeView.replace(CompositeView.java:217)
	at javax.swing.text.BoxView.replace(BoxView.java:181)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:114)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setView(BasicTextUI.java:1328)
	at javax.swing.plaf.basic.BasicTextUI.setView(BasicTextUI.java:693)
	at javax.swing.plaf.basic.BasicTextUI.modelChanged(BasicTextUI.java:682)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.propertyChange(BasicTextUI.java:1794)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8436)
	at javax.swing.text.JTextComponent.setDocument(JTextComponent.java:443)
	at javax.swing.JEditorPane.setEditorKit(JEditorPane.java:1055)
	at com.intellij.ui.components.JBLabel.setCopyable(JBLabel.java:268)
	at com.intellij.ui.components.JBLabel.updateUI(JBLabel.java:205)
	at com.intellij.util.IJSwingUtilities.updateComponentTreeUI(IJSwingUtilities.java:152)
	at com.intellij.ide.ui.laf.LafManagerImpl.b(LafManagerImpl.java:703)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.java:472)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$1EditorColorSchemeProcessor.onCurrentSchemeSwitched(EditorColorsManagerImpl.java:109)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$1EditorColorSchemeProcessor.onCurrentSchemeSwitched(EditorColorsManagerImpl.java:82)
	at com.intellij.configurationStore.SchemeManagerImpl.setCurrent(SchemeManagerImpl.kt:902)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.setGlobalScheme(EditorColorsManagerImpl.java:323)
	at com.intellij.ide.ui.laf.darcula.DarculaInstaller.a(DarculaInstaller.java:60)
	at com.intellij.ide.ui.laf.darcula.DarculaInstaller.uninstall(DarculaInstaller.java:35)
	at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:348)
	at com.chrisrm.idea.actions.themes.MTOneDarkThemeAction.setSelected(MTOneDarkThemeAction.java:42)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:117)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:117)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:355)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:343)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:767)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ptrkcsk** [comment]
I just realized that this is fixed in the EAP.

**Comment by mallowigi** [comment]
Thanks for the input. I wonder whether this bug has always been around or is just new caused by changes in the API.

Glad it worked because I don't have the time to test it thoroughly

**Comment by ptrkcsk** [comment]
I'm actually still experiencing this problem regularly, on both stable and EAP versions of PhpStorm and Material Theme UI.

**Comment by mallowigi** [comment]
I think I fixed it this time.

**Comment by ptrkcsk** [comment]
I just updated to PhpStorm 2017.3.3 and Material Theme UI v1.6.0.1, and I am still experiencing the bug. I'm able to reproduce it consistently using the steps in my first comment.

**Comment by ptrkcsk** [comment]
I just opened a new, very simple, project, then disabled all plugins and re-enabled them one by one, after which I had no problem switching between themes.

I'll try the same approach in the large project in which I first encountered the bug, and see if I can narrow it down to a plugin conflict.

**Comment by mallowigi** [comment]
Thanks! This is really odd as I’m using the plugin at least 12 h a day and in different editors (IntelliJ, Rubymine and Webstorm) but I can’t reproduce your problem. It could be something related with phpstorm but I’ll highly doubt it.

If you can pinpoint the problem it would be greatly appreciated

**Comment by ptrkcsk** [comment]
I just spent a few hours experimenting with projects and plugins.

Here's what I did:

- Opened a project in PhpStorm. For this experiment I opened a WordPress plugin I have written called [FA WP Admin Menu Icons](https://github.com/ptrkcsk/fa-wp-admin-menu-icons) I have written. This project has existed on my hard drive for a few months.
- Disabled all plugins. The bug disappeared.
- Enabled JetBrains plugins (no unofficial plugins) individually until the bug re-appeared. The culprit seems to be the JetBrains 'Git Integration' plugin. If I enable all JetBrains plugins except for 'Git Integration' (and 'GitHub', which depends on 'Git Integration'), and the bug disappears. If I then enable 'Git Integration', the bug reappears.

Here's where it gets interesting:

- Cloned FA WP Admin Menu Icons (the exact same project which I used for the steps above) in a new location.
- Opened the project in PhpStorm. Enabled all JetBrains plugins, including 'Git Integration'. The bug does not exist. Enabling or disabling 'Git Integration' has no effect.

So, in my case at least, it seems to be a combination of the 'Git Integration' plugin and working on the project for some time. The mystery is what action introduces the bug. I'll keep you posted in case I find anything!

**Comment by ptrkcsk** [comment]
Okay, I think I have found a combination of steps which can be reproduced:

- Open a project
- Switch themes
- Open the Version Control Tool Window
- In the Version Control Tool Window, enable Preview Diff
- Switch themes again
- IDE breaks and throws fatal error

**Comment by mallowigi** [comment]
lol I can't even commit my work...

**Comment by mallowigi** [comment]
Fixed! At least your issue looks fixed now. Hope its' the end of that!

**Comment by ptrkcsk** [comment]
Just tested it out and it looks resolved to me. Thank you so much for your effort!

**Comment by wq709474448** [comment]
IDEA after use there is a BUG, ctrl+F input Chinese is a garbled code, and ctrl+shift+F or +R output Chinese are all garbled.

**Comment by mallowigi** [comment]
it's because of the font Fira Code, it's not suited for non latin text. You can change it in Settings > Editor > Color Scheme > Color Scheme font and choose a chinese font there.

**Comment by wq709474448** [comment]
You can't find the settings you say
![qq 20180525093358](https://user-images.githubusercontent.com/36838284/40521635-19f6e3b8-5fff-11e8-86aa-42bc35d4588c.png)
The following diagram isBUG
![111](https://user-images.githubusercontent.com/36838284/40521660-3eab4032-5fff-11e8-908f-322caea2def9.png)
![123](https://user-images.githubusercontent.com/36838284/40521661-3f00b0bc-5fff-11e8-94cd-c6190e9d301a.png)
![222](https://user-images.githubusercontent.com/36838284/40521662-3f5a1b0c-5fff-11e8-907a-703acfc989e1.png)
This is the way to enter Chinese.
