### ISSUE TITLE
Can't see annotations with Darker theme

### ISSUE THREAD

**Issue by TomCorvus** [ChrisRM/material-theme-jetbrains#460]
First, thanks for your job!  Really cool schemes!

### Summary
Can't see Annonations propery with the Darker theme

### Steps to reproduce (if needed)

1. Select the darker theme
2. Right click on line numbers column
3. Check Annotate (GIT init needed)

Here a screenshot:
![screen001](https://user-images.githubusercontent.com/3451011/31497599-dd403bfe-af5f-11e7-949b-2278de83d6be.jpg)

### Environment

PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017
Licensed to Thomas

JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by say8425** [comment]
I have same issue

**Comment by lerocha** [comment]
Same issue here with IntelliJ

**Environment**
Material Theme UI Version: 1.0.1

IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 25, 2017
Licensed to Luis Rocha

JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
Should be fixed in versions 1.1.x (EAP only for now)

**Comment by say8425** [comment]
<img width="1400" alt="2017-10-30 10 44 39" src="https://user-images.githubusercontent.com/3258867/32151358-9c255b96-bd5f-11e7-8d14-acc82308dac6.png">
No. It's not fixed, yet.
